[browser]
gatherUsageStats = false

[server]
headless = true

[theme]
base = "light"
primaryColor = "#0ea5e9"
backgroundColor = "#f7f9fc"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "sans serif"
